version: "2.1"
services:

  example-consumer-test:
    extends:
      file: docker-compose-base.yml
      service: example-consumer-base
    networks:
      - test_net

networks:
  test_net:
    external:
      name: aether_test
