version: "2.1"
services:

  rest-consumer:
    extends:
      file: docker-compose-base.yml
      service: rest-consumer-base
    environment:
      REDIS_HOST: redis
    ports:
      - "${EXPOSE_PORT}:${EXPOSE_PORT}"
    networks:
      - aether
  
  redis:
    extends:
      file: docker-compose-base.yml
      service: redis-base
    networks:
      - aether

networks:
  aether:
    external:
      name: aether_internal
