version: "2.1"
services:

  rest-consumer-test:
    extends:
      file: docker-compose-base.yml
      service: rest-consumer-base
    environment:
      REDIS_HOST: redis-test
    ports:
      - "${EXPOSE_PORT}:${EXPOSE_PORT}"
    networks:
      - test_net
    links:
      - redis-test
    depends_on:
      redis-test:
        condition: service_started

  redis-test:
    extends:
      file: docker-compose-base.yml
      service: redis-base
    networks:
      - test_net

  # ---------------------------------
  # Mock Data Container
  # ---------------------------------
  assets-test:
    build:
      context: ./aether-bootstrap/assets/generation
      dockerfile: Dockerfile
    volumes:
      - ./aether-bootstrap/assets:/code/assets
    environment:
      KERNEL_URL: http://kernel-test:9000
      KERNEL_USER: ${TEST_KERNEL_ADMIN_USERNAME}
      KERNEL_PASSWORD: ${TEST_KERNEL_ADMIN_PASSWORD}
      PROJECT_NAME: DefaultDemo
      SUBMISSION_ENDPOINT: default_mapping
    networks:
      - test_net


networks:
  test_net:
    external:
      name: aether_test
