version: "2.1"

services:
  rest-consumer-base:
    image: ehealthafrica/aether-rest-consumer
    build: ./consumer
    stdin_open: true
    tty: true
    environment:
     - ADMIN_USER=${ADMIN_USER}
     - ADMIN_PW=${ADMIN_PW}
     - PYTHONUNBUFFERED=1
     - KAFKA_CONFIG_PATH=/code/conf/consumer/kafka.json
     - CONSUMER_CONFIG_PATH=/code/conf/consumer/consumer.json
     - EXPOSE_PORT=${EXPOSE_PORT}
     - REDIS_PORT=6379
     - REDIS_DB=0

    volumes:
     - ./consumer/conf:/code/conf
    command: start

  redis-base:
    image: redis:3-alpine
    command: ["--notify-keyspace-events", "KA"]
