version: "2.1"
services:

  rest-consumer-test:
    extends:
      file: docker-compose-base.yml
      service: example-consumer-base
    ports:
      - "${EXPOSE_PORT}:${EXPOSE_PORT}"
    networks:
      - test_net

networks:
  test_net:
    external:
      name: aether_test
