version: "2.1"
services:
  rest-consumer-base:
    image: ehealthafrica/aether-rest-consumer
    build: ./consumer
    stdin_open: true
    tty: true
    environment:
     - PYTHONUNBUFFERED=1
     - KAFKA_CONFIG=/code/conf/consumer/kafka.json
     - CONSUMER_CONFIG=/code/conf/consumer/consumer.json
     - EXPOSE_PORT=${EXPOSE_PORT}

    volumes:
     - ./consumer/conf:/code/conf
    command: start
